version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docker/hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./docker/logs:/var/log/nginx
    links:
      - php
  php:
    build: ./docker/images/php
    links:
      - mysql
    volumes:
      - ./www:/var/www
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: a1-l2.live
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8183:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: a1-l2.live